"""
Persistence-layer model for reflection content stored in Postgres.

This maps directly to the per-agent ``agent_{N}.reflections`` table and is
deliberately separate from the domain model in
``atman.core.models.reflection.ReflectionEvent`` (which tracks reflection
process metadata, not row layout). ``ReflectionLevel`` is re-used from the
core domain model so the two layers stay in sync.
"""

from datetime import UTC, datetime
from typing import Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, field_validator

from atman.core.models.reflection import ReflectionLevel

__all__ = ["ReflectionEvent", "ReflectionLevel"]


class ReflectionEvent(BaseModel):
    """
    Persistent storage model for reflection content.

    This maps directly to the per-agent reflections table and stores
    the actual reflection content generated by LLMs, separate from
    the domain model in atman.core.models.reflection which tracks
    reflection process metadata.
    """

    id: int | None = Field(
        default=None,
        description="Primary key (BIGSERIAL), None for new records",
    )
    agent_id: UUID = Field(description="Agent UUID, references agents(id)")
    level: ReflectionLevel = Field(description="Reflection level: micro/daily/deep")
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        description="When this reflection was created",
    )
    session_id: UUID | None = Field(
        default=None,
        description="Session reference for micro reflections, NULL for daily/deep",
    )
    period_start: datetime | None = Field(
        default=None,
        description="Time window start for daily/deep reflections, NULL for micro",
    )
    period_end: datetime | None = Field(
        default=None,
        description="Time window end for daily/deep reflections, NULL for micro",
    )
    content: str = Field(description="Main reflection content generated by LLM")
    summary: str | None = Field(
        default=None,
        description="Optional short title/summary",
    )
    session_refs: list[UUID] = Field(
        default_factory=list,
        description=(
            "IDs of sessions analyzed in this reflection (R15 — was 'experience_refs'; "
            "one virtual SessionExperience per Session, so the ids match by construction)"
        ),
    )
    reframing_note_ids: list[UUID] = Field(
        default_factory=list,
        description="IDs of reframing notes produced by this reflection",
    )
    model_provider: str | None = Field(
        default=None,
        description="LLM provider (ollama, anthropic, etc.)",
    )
    model_name: str | None = Field(
        default=None,
        description="Model name (e.g., qwen3.5:9b)",
    )
    schema_version: int = Field(
        default=1,
        description="Schema version for migrations",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional metadata as JSONB",
    )

    @field_validator("content")
    @classmethod
    def validate_content_not_empty(cls, v: str) -> str:
        """Ensure content is not empty."""
        if not v or not v.strip():
            raise ValueError("content cannot be empty")
        return v.strip()

    @field_validator("summary", mode="before")
    @classmethod
    def strip_summary(cls, v: str | None) -> str | None:
        """Strip summary if provided."""
        if v is not None:
            return v.strip() if v.strip() else None
        return v

    @field_validator("model_provider", "model_name", mode="before")
    @classmethod
    def strip_model_fields(cls, v: str | None) -> str | None:
        """Strip model fields if provided."""
        if v is not None:
            return v.strip() if v.strip() else None
        return v

    model_config = ConfigDict(
        validate_assignment=True,
        json_schema_extra={
            "example": {
                "agent_id": "123e4567-e89b-12d3-a456-426614174000",
                "level": "daily",
                "content": "I noticed a pattern in my recent interactions where I tend to...",
                "summary": "Pattern of over-explaining",
                "session_refs": [],
                "reframing_note_ids": [],
                "model_provider": "ollama",
                "model_name": "qwen3.5:9b",
                "schema_version": 1,
                "metadata": {},
            }
        },
    )
