-- =============================================================================
-- Migration 0001: Create reflections table
-- Description: Core schema for reflection storage (micro/daily/deep)
-- Author: E27 — Core Reflections Schema
-- Date: 2026-05-10
-- =============================================================================

-- ── Reflection Level Enum ────────────────────────────────────────────────────

-- Create enum type for reflection levels if it doesn't exist
DO $$ BEGIN
    CREATE TYPE reflection_level AS ENUM ('micro', 'daily', 'deep');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

COMMENT ON TYPE reflection_level IS 'Reflection depth: micro (after session), daily (end of day), deep (scheduled deep reflection)';

-- ── Reflections Table ─────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS reflections (
    id                   BIGSERIAL PRIMARY KEY,
    agent_id             UUID NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
    level                reflection_level NOT NULL,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    
    -- Session context (for micro reflections)
    session_id           UUID REFERENCES sessions(id) ON DELETE SET NULL,
    
    -- Time period context (for daily/deep reflections)
    period_start         TIMESTAMPTZ,
    period_end           TIMESTAMPTZ,
    
    -- Content
    content              TEXT NOT NULL,
    summary              TEXT,
    
    -- References
    experience_refs      UUID[] NOT NULL DEFAULT '{}',
    reframing_note_ids   UUID[] NOT NULL DEFAULT '{}',
    
    -- Model metadata (for traceability)
    model_provider       TEXT,
    model_name           TEXT,
    
    -- Schema versioning and metadata
    schema_version       INTEGER NOT NULL DEFAULT 1,
    metadata             JSONB NOT NULL DEFAULT '{}'
);

COMMENT ON TABLE reflections IS 'Unified reflection storage for micro/daily/deep reflection levels. Supports E0.3 eval.reflection_quality FK.';
COMMENT ON COLUMN reflections.level IS 'micro: after-session; daily: end-of-day pattern detection; deep: scheduled health assessment';
COMMENT ON COLUMN reflections.session_id IS 'Populated only for level=''micro''; NULL for daily/deep';
COMMENT ON COLUMN reflections.period_start IS 'Populated for level=''daily''/''deep''; NULL for micro';
COMMENT ON COLUMN reflections.period_end IS 'Populated for level=''daily''/''deep''; NULL for micro';
COMMENT ON COLUMN reflections.content IS 'Free-form reflection text generated by reflection model (OllamaReflectionModel, etc.)';
COMMENT ON COLUMN reflections.experience_refs IS 'UUIDs of experiences.id analyzed in this reflection';
COMMENT ON COLUMN reflections.reframing_note_ids IS 'UUIDs of reframing_notes.id produced by this reflection';
COMMENT ON COLUMN reflections.model_provider IS 'LLM provider: ollama, anthropic, etc. — for traceability';
COMMENT ON COLUMN reflections.model_name IS 'Specific model: e.g. qwen3:14b';
COMMENT ON COLUMN reflections.schema_version IS 'Schema version for future migrations (current: 1)';

-- ── Indexes ───────────────────────────────────────────────────────────────────

-- Timeline queries: most recent reflections for an agent
CREATE INDEX IF NOT EXISTS idx_reflections_agent_time
    ON reflections(agent_id, created_at DESC);

-- Level-filtered queries: e.g. all daily reflections for an agent
CREATE INDEX IF NOT EXISTS idx_reflections_level_time
    ON reflections(level, created_at DESC);

-- Experience cross-reference: which reflections analyzed a specific experience
CREATE INDEX IF NOT EXISTS idx_reflections_experience_refs
    ON reflections USING GIN(experience_refs);

-- Session lookup: find reflection for a specific session (micro level)
CREATE INDEX IF NOT EXISTS idx_reflections_session
    ON reflections(session_id) WHERE session_id IS NOT NULL;

-- ── Row-Level Security (RLS) ──────────────────────────────────────────────────

ALTER TABLE reflections ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS reflections_isolation ON reflections;
CREATE POLICY reflections_isolation ON reflections
    USING (agent_id = NULLIF(current_setting('atman.current_agent', TRUE), '')::UUID);

COMMENT ON POLICY reflections_isolation ON reflections IS 'RLS: agent_id must match atman.current_agent session variable';

-- =============================================================================
-- End of Migration 0001
-- =============================================================================
