-- Migration: Create reflections table
-- Issue: E27 - Core Reflections Schema
--
-- This migration creates the reflections table to store reflection content
-- across all three levels (micro, daily, deep) for persistent storage.

-- Create enum for reflection levels
DO $$ BEGIN
    CREATE TYPE reflection_level AS ENUM ('micro', 'daily', 'deep');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Create reflections table
CREATE TABLE IF NOT EXISTS public.reflections (
    id BIGSERIAL PRIMARY KEY,
    agent_id UUID NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
    level reflection_level NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    session_id UUID REFERENCES sessions(id),
    period_start TIMESTAMPTZ,
    period_end TIMESTAMPTZ,
    content TEXT NOT NULL,
    summary TEXT,
    experience_refs UUID[] NOT NULL DEFAULT '{}',
    reframing_note_ids UUID[] NOT NULL DEFAULT '{}',
    model_provider TEXT,
    model_name TEXT,
    schema_version INTEGER NOT NULL DEFAULT 1,
    metadata JSONB NOT NULL DEFAULT '{}'
);

-- Comments
COMMENT ON TABLE public.reflections IS 'Reflection content across micro/daily/deep levels';
COMMENT ON COLUMN public.reflections.level IS 'Reflection depth: micro (per-session), daily (pattern detection), deep (narrative integration)';
COMMENT ON COLUMN public.reflections.session_id IS 'Session reference for micro reflections, NULL for daily/deep';
COMMENT ON COLUMN public.reflections.period_start IS 'Time window start for daily/deep reflections, NULL for micro';
COMMENT ON COLUMN public.reflections.period_end IS 'Time window end for daily/deep reflections, NULL for micro';
COMMENT ON COLUMN public.reflections.content IS 'Main reflection content generated by LLM';
COMMENT ON COLUMN public.reflections.summary IS 'Optional short title/summary';
COMMENT ON COLUMN public.reflections.experience_refs IS 'IDs of experiences analyzed in this reflection';
COMMENT ON COLUMN public.reflections.reframing_note_ids IS 'IDs of reframing notes produced by this reflection';
COMMENT ON COLUMN public.reflections.model_provider IS 'LLM provider (ollama, anthropic, etc.)';
COMMENT ON COLUMN public.reflections.model_name IS 'Model name (e.g., qwen3:14b)';
COMMENT ON COLUMN public.reflections.schema_version IS 'Schema version for migrations';

-- Indexes
CREATE INDEX IF NOT EXISTS idx_reflections_agent_created ON public.reflections(agent_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_reflections_level_created ON public.reflections(level, created_at);
CREATE INDEX IF NOT EXISTS idx_reflections_experience_refs ON public.reflections USING GIN(experience_refs);

-- Row Level Security
ALTER TABLE public.reflections ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS reflections_isolation ON public.reflections;
CREATE POLICY reflections_isolation ON public.reflections
    USING (agent_id = NULLIF(current_setting('atman.current_agent', TRUE), '')::UUID);